[versions]
kotlin = "2.1.20"

[libraries]
dokka-java-plugin = "org.jetbrains.dokka:kotlin-as-java-plugin:2.0.0"

[plugins]
deployer = { id = "io.deepmedia.tools.deployer", version = "0.18.0" }
dokka = { id = "org.jetbrains.dokka", version = "2.0.0" }
kotlin-sam-with-receiver = { id = "org.jetbrains.kotlin.plugin.sam.with.receiver", version.ref = "kotlin" }